package hr.dp333.enums;

public enum DataColumn {

	VOTER_REGISTRATION_DATE(8), COUNTY_FIPS(9), COUNTY_NAME(10), COUNTY_LATITUDE(24), COUNTY_LONGITUDE(25), DEMOCRAT_ACTIVE(11), REPUBLICAN_ACTIVE(12),
	LIBERTARIAN_ACTIVE(13), NO_PARTY_ACTIVE(14), OTHER_ACTIVE(15), TOTAL_ACTIVE(16), DEMOCRAT_INACTIVE(17), REPUBLICAN_INACTIVE(18), LIBERTARIAN_INACTIVE(19),
	NO_PARTY_INACTIVE(20), OTHER_INACTIVE(21), TOTAL_INACTIVE(22), GRAND_TOTAL(23);

	private final int row;

	private DataColumn(int row) {
		this.row = row;
	}

	public int getRow() {
		return this.row;
	}

}
